version: "2"
linters:
  default: standard
  enable:
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unparam
    - whitespace
  settings:
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - hugeParam # We don't care about huge parameters much. Too many false positives.
        - rangeValCopy # We don't care about range copies much. Too many false positives.
        - unnecessaryBlock # Sometimes we need to use blocks for readability.
        - ptrToRefParam # Too many false positives.
        - exitAfterDefer # Too many false positives.
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gosec:
      excludes:
        - G115 # Annoying and have a lot of false-positive results.
    lll:
      line-length: 140
    misspell:
      locale: US
    staticcheck:
      checks:
        - "*"
        - "-QF1001" # Suggested simplification via De Morgan's law is not always better.
        - "-QF1008" # Too much false positives, embedding is fine.
  exclusions:
    generated: lax
    rules:
      # Disable linters that are annoying in tests.
      - linters:
          - dupl
          - errcheck
          - funlen
          - gocognit
          - goconst
          - gocyclo
          - gosec
          - lll
          - scopelint
        path: _test\.go
      - linters:
          - revive
        path: _test\.go
        text: unused-parameter

      # Allow unused context.Context
      - linters:
          - revive
        text: unused-parameter
        source: .+\s+context.Context

      # Do not need comments in internal/binary packages.
      - linters:
          - revive
          - staticcheck
        path: (internal|cmd)
        text: comment

      # It's okay for commands to write files and exec binaries.
      - linters:
          - gosec
        path: cmd
        text: G(307|306|301|204)
formatters:
  enable:
    - goimports
    - gofumpt
  settings:
    goimports:
      local-prefixes:
        - github.com/oteldb/promql-engine
